{"timestamp":"2025-07-22T02:00:21.025560","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-07-22T02:00:21.025985","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/orchestrator.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-22T02:00:21.109568Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-22T02:00:21.110425Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-22T02:00:21.110814Z","level":"info","event":"Current task name:transform_weather_data","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-22T02:00:21.111067Z","level":"info","event":"Dag name:weather_data_orchestrator","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-22T02:00:21.123046","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"OSError","exc_value":"Cannot save file into a non-existent directory: '/opt/airflow/data'","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":877,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1164,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":217,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":240,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/weather-data-project/api_request/data_transform.py","lineno":7,"name":"clean_weather_data"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/util/_decorators.py","lineno":333,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py","lineno":3967,"name":"to_csv"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py","lineno":1014,"name":"to_csv"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py","lineno":251,"name":"save"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py","lineno":749,"name":"get_handle"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py","lineno":616,"name":"check_parent_directory"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-22T02:00:21.124120Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-22T02:00:21.124383Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-22T02:00:21.124634Z","level":"info","event":"Task:<Task(PythonOperator): transform_weather_data>","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-22T02:00:21.124819Z","level":"info","event":"Failure caused by Cannot save file into a non-existent directory: '/opt/airflow/data'","chan":"stdout","logger":"task"}
